# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolas Deparis
email: nicolas.deparis@astro.unistra.fr
description: > # this means to ignore newlines until "baseurl:"
  PhD student in astro, cosmo, simulation, blabla... blabla...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  NicolasDeparis

# Build settings
markdown: kramdown
